<a href="https://colab.research.google.com/github/sumukhbhat12/Tensor-Flow-Course-FreeCodeCamp/blob/main/Tensor_Flow_course_FreeCodeCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import TensorFlow

In [8]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Creating Tensors

In [3]:
string = tf.Variable("Hello world", tf.string)
number = tf.Variable(20, tf.int16)
floating = tf.Variable(23.55, tf.float64)

Rank/Degree of Tensors -
number of dimensions in the tensor.
tensor of Rank 0 is a scalar.

In [4]:
rank1_tensor = tf.Variable(['Hello', 'World'], tf.string)
rank2_tensor = tf.Variable([['Hello', 'World'], ['I am', 'Sumukh']], tf.string)

In [5]:
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Hello', b'World'],
       [b'I am', b'Sumukh']], dtype=object)>


In [6]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Changing Shape

In [17]:
arr = np.array(rank2_tensor).reshape(4,)
print(arr)

arr = arr.reshape(2,2)
print(arr)

arr = arr.reshape(4,1) #same as (-1,1)
print(arr)

arr = arr.reshape(1,4) #same as (1,-1), (-1,4),
print(arr)

[b'Hello' b'World' b'I am' b'Sumukh']
[[b'Hello' b'World']
 [b'I am' b'Sumukh']]
[[b'Hello']
 [b'World']
 [b'I am']
 [b'Sumukh']]
[[b'Hello' b'World' b'I am' b'Sumukh']]
[[b'Hello' b'World' b'I am' b'Sumukh']]


[2,2,3] --> first number represents number of items, second and third represent the shape in rows and cols

In [25]:
tensor1 = tf.ones([2,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [31]:
tensor1 = tf.reshape(tensor1, [2,3,2])
print(tensor1)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(2, 3, 2), dtype=float32)


In [32]:
tensor1 = tf.reshape(tensor1, [6,-1])
print(tensor1)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]], shape=(6, 2), dtype=float32)


In [33]:
tensor1 = tf.reshape(tensor1, [-1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [ ]:
t = tf.zeros([5,5,5,5])

t = tf.reshape(t, [-1,1])
print(t)